#!/usr/bin/env python3
"""Create and visualize relative depth labels from X-AnyLabeling output.

Validates float32 .npy depth maps generated by Depth Anything V2, then
collects them into a single destination folder with standardized naming.

Modes:
    --convert   Scan all scenarios under root, validate .npy depth maps
                (float32, [0, 1]), and collect valid ones into dst.
                Invalid files are skipped with a warning.
    --viz       Visualize depth maps overlaid on original images.
                Requires opencv-python (not headless) for cv2.imshow.

Config required (in model YAML):
    min_depth: 0.0
    max_depth: 1.0
    save_raw_depth: true

X-AnyLabeling saves depth to (source modified):
    <scenario>/<subdir>/CAMERA_X/depth/{timestamp}_depth.npy

Output naming: <scenario>_<camera>_<timestamp>.npy
    e.g. a1_scenario_00_1_0.npy

Load example:
    depth = np.load(path)  # (H, W), float32, [0.0, 1.0]

Expected directory structure:
    <root>/
        <scenario_00>/
            <subdir>/          # default: "Noon"
                CAMERA_1/
                    0.jpg
                    100.jpg
                    ...
                    depth/   # generated by X-AnyLabeling
                        0_depth.npy
                        ...
                CAMERA_2/
                    ...
        <scenario_01>/
        ...

Dependencies:
    pip install numpy opencv-python
"""

import argparse
import sys
from pathlib import Path

import cv2
import numpy as np


# ── Validation ────────────────────────────────────────────

def validate_depth(npy_path: Path) -> tuple[bool, str]:
    """Validate a depth .npy file. Returns (is_valid, message)."""
    try:
        depth = np.load(npy_path)
    except Exception as e:
        return False, f"failed to load: {e}"

    if depth.dtype != np.float32:
        return False, f"dtype={depth.dtype}, expected float32"

    if depth.ndim != 2:
        return False, f"ndim={depth.ndim}, expected 2"

    dmin, dmax = float(depth.min()), float(depth.max())
    if dmin < 0.0 or dmax > 1.0:
        return False, f"range=[{dmin:.6f}, {dmax:.6f}], expected [0.0, 1.0]"

    return True, f"shape={depth.shape}, range=[{dmin:.4f}, {dmax:.4f}]"


# ── Convert ────────────────────────────────────────────────

def find_camera_dirs(root: Path, subdir: str, cameras: list[int]) -> list[tuple[str, int, Path]]:
    """Return list of (scenario_name, camera_number, camera_dir_path)."""
    results = []
    for scenario_dir in sorted(root.iterdir()):
        if not scenario_dir.is_dir():
            continue
        for cam_num in cameras:
            cam_dir = scenario_dir / subdir / f"CAMERA_{cam_num}"
            if cam_dir.is_dir():
                results.append((scenario_dir.name, cam_num, cam_dir))
    return results


def convert(root: Path, dst: Path, subdir: str, cameras: list[int], depth_dir_name: str):
    dst.mkdir(parents=True, exist_ok=True)
    cam_entries = find_camera_dirs(root, subdir, cameras)

    if not cam_entries:
        print(f"No CAMERA directories found under {root}/*/{subdir}")
        sys.exit(1)

    total, valid_count, skipped = 0, 0, 0
    valid_files: list[tuple[Path, Path]] = []  # (src_npy, dst_npy)

    for scenario, cam_num, cam_dir in cam_entries:
        depth_dir = cam_dir / depth_dir_name
        if not depth_dir.is_dir():
            continue

        # Find images in this camera dir to match timestamps
        image_stems = {p.stem for p in cam_dir.iterdir()
                       if p.suffix.lower() in (".jpg", ".jpeg", ".png", ".bmp")}

        if not image_stems:
            continue

        # Find matching depth files
        matched = []
        for stem in sorted(image_stems):
            npy_path = depth_dir / f"{stem}_depth.npy"
            if npy_path.exists():
                matched.append((stem, npy_path))

        if not matched:
            continue

        print(f"[{scenario}/CAMERA_{cam_num}] {len(matched)} depth file(s)")

        for timestamp, npy_path in matched:
            total += 1
            is_valid, msg = validate_depth(npy_path)
            out_name = f"{scenario}_{cam_num}_{timestamp}.npy"
            out_path = dst / out_name

            if not is_valid:
                print(f"  [INVALID] {npy_path.name}: {msg} -- skipped")
                skipped += 1
                continue

            valid_files.append((npy_path, out_path))
            valid_count += 1
            print(f"  [OK] {npy_path.name} -> {out_name}  ({msg})")

    if skipped > 0:
        print(f"\n{skipped}/{total} file(s) failed validation -- not copied")

    if not valid_files:
        print(f"\nNo valid depth files to copy.")
        sys.exit(1)

    # Copy all valid files
    print(f"\nCopying {valid_count} validated file(s) to {dst} ...")
    for src_npy, dst_npy in valid_files:
        data = np.load(src_npy)
        np.save(dst_npy, data)

    # Verify copy
    verify_ok = 0
    for _, dst_npy in valid_files:
        if dst_npy.exists() and dst_npy.stat().st_size > 0:
            verify_ok += 1
        else:
            print(f"  [WARN] copy verification failed: {dst_npy.name}")

    print(f"Done: {verify_ok}/{valid_count} copied -> {dst}")
    if verify_ok < valid_count:
        print(f"  WARNING: {valid_count - verify_ok} file(s) may be missing!")
        sys.exit(1)


# ── Visualize ──────────────────────────────────────────────

def depth_to_colormap(depth: np.ndarray) -> np.ndarray:
    """Convert float32 depth [0,1] to TURBO colormap BGR image."""
    depth_uint8 = (depth * 255.0).astype(np.uint8)
    return cv2.applyColorMap(depth_uint8, cv2.COLORMAP_TURBO)


def parse_depth_filename(name: str) -> tuple[str, int, str] | None:
    """Parse <scenario>_<camera>_<timestamp>.npy -> (scenario, cam_num, timestamp)."""
    parts = name.removesuffix(".npy").rsplit("_", 2)
    if len(parts) != 3:
        return None
    scenario, cam_str, timestamp = parts
    if not cam_str.isdigit():
        return None
    return scenario, int(cam_str), timestamp


def build_depth_info(depth: np.ndarray, scale: int = 20) -> np.ndarray:
    """Build info panel showing depth statistics."""
    lines = [
        f"dtype: {depth.dtype}",
        f"shape: {depth.shape}",
        f"min:   {depth.min():.4f}",
        f"max:   {depth.max():.4f}",
        f"mean:  {depth.mean():.4f}",
        f"std:   {depth.std():.4f}",
    ]
    panel_h = len(lines) * (scale + 5) + 10
    panel_w = 200
    panel = np.zeros((panel_h, panel_w, 3), dtype=np.uint8)
    for i, line in enumerate(lines):
        y = 10 + i * (scale + 5) + scale - 4
        cv2.putText(panel, line, (5, y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.40, (255, 255, 255), 1)
    return panel


def render_depth_frame(root: Path, subdir: str, npy_path: Path,
                       scale: float = 0.5) -> np.ndarray | None:
    """Render depth visualization in 2x2 grid layout, scaled down.

    Layout:
        [original image] [depth colormap]
        [overlay       ] [info panel    ]
    """
    parsed = parse_depth_filename(npy_path.name)
    if parsed is None:
        return None

    scenario, cam_num, timestamp = parsed
    # Try common image extensions
    img_path = None
    for ext in (".jpg", ".jpeg", ".png", ".bmp"):
        candidate = root / scenario / subdir / f"CAMERA_{cam_num}" / f"{timestamp}{ext}"
        if candidate.exists():
            img_path = candidate
            break
    if img_path is None:
        return None

    img = cv2.imread(str(img_path))
    depth = np.load(str(npy_path))
    if img is None or depth is None:
        return None

    # Apply colormap
    depth_color = depth_to_colormap(depth)
    if depth_color.shape[:2] != img.shape[:2]:
        depth_color = cv2.resize(depth_color, (img.shape[1], img.shape[0]),
                                 interpolation=cv2.INTER_CUBIC)

    # Overlay
    overlay = cv2.addWeighted(img, 0.2, depth_color, 0.8, 0)

    # Scale down each cell
    h, w = img.shape[:2]
    new_w, new_h = int(w * scale), int(h * scale)
    img_s = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_AREA)
    depth_s = cv2.resize(depth_color, (new_w, new_h), interpolation=cv2.INTER_AREA)
    overlay_s = cv2.resize(overlay, (new_w, new_h), interpolation=cv2.INTER_AREA)

    # Info panel — match cell size
    info = build_depth_info(depth)
    info_canvas = np.zeros((new_h, new_w, 3), dtype=np.uint8)
    # Paste info into top-left of canvas
    ih, iw = min(info.shape[0], new_h), min(info.shape[1], new_w)
    info_canvas[:ih, :iw] = info[:ih, :iw]

    # 2x2 grid
    top_row = np.hstack([img_s, depth_s])
    bot_row = np.hstack([overlay_s, info_canvas])
    return np.vstack([top_row, bot_row])


def viz(root: Path, dst: Path, subdir: str, scale: float = 0.5):
    npy_files = sorted(dst.glob("*.npy"))
    if not npy_files:
        print(f"No .npy files found in {dst}")
        sys.exit(1)

    valid = [(i, f) for i, f in enumerate(npy_files) if parse_depth_filename(f.name)]
    if not valid:
        print("No valid depth files found.")
        sys.exit(1)

    print(f"Found {len(valid)} depth file(s) in {dst} (scale={scale})")
    print("  Arrow Right = next, Arrow Left = prev, ESC = quit")

    KEY_ESC = 27
    KEY_RIGHT_GTK = 83
    KEY_RIGHT_QT = 65363
    KEY_LEFT_GTK = 81
    KEY_LEFT_QT = 65361

    idx = 0
    win_name = "create_depth - viz"
    prev_idx = -1
    while True:
        idx = max(0, min(idx, len(valid) - 1))
        if idx != prev_idx:
            _, nf = valid[idx]
            canvas = render_depth_frame(root, subdir, nf, scale=scale)
            if canvas is not None:
                cv2.imshow(win_name, canvas)
                cv2.setWindowTitle(win_name, f"[{idx+1}/{len(valid)}] {nf.name}")
                print(f"  [{idx+1}/{len(valid)}] {nf.name}")
            else:
                print(f"  [{idx+1}/{len(valid)}] {nf.name} -- render failed (image not found?)")
            prev_idx = idx

        key = cv2.waitKeyEx(0) & 0xFFFF
        if key == KEY_ESC:
            break
        elif key in (KEY_LEFT_GTK, KEY_LEFT_QT):
            idx -= 1
        elif key in (KEY_RIGHT_GTK, KEY_RIGHT_QT):
            idx += 1

    cv2.destroyAllWindows()


# ── CLI ────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--convert", action="store_true",
                      help="validate and collect depth .npy files")
    mode.add_argument("--viz", action="store_true",
                      help="visualize depth maps overlaid on images")

    parser.add_argument("--root", type=str, required=True,
                        help="root directory containing scenario folders")
    parser.add_argument("--dst", type=str, default=None,
                        help="destination folder for depth labels (default: <root>/depth_labels)")
    parser.add_argument("--subdir", type=str, default="Noon",
                        help="sub-directory under each scenario (default: Noon)")
    parser.add_argument("--cameras", type=str, default="1,2,3,4,5",
                        help="comma-separated camera numbers (default: 1,2,3,4,5)")
    parser.add_argument("--depth-dir", type=str, default="depth",
                        help="name of depth output directory (default: depth)")
    parser.add_argument("--scale", type=float, default=0.5,
                        help="display scale for viz mode (default: 0.5)")
    args = parser.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        print(f"Error: {root} is not a directory")
        sys.exit(1)

    dst = Path(args.dst) if args.dst else root / "depth_labels"
    cameras = [int(c) for c in args.cameras.split(",")]

    if args.convert:
        convert(root, dst, args.subdir, cameras, args.depth_dir)
    elif args.viz:
        viz(root, dst, args.subdir, scale=args.scale)


if __name__ == "__main__":
    main()
